
;with FULLDB AS (
	SELECT table_name, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'delivery_point'
),
SMALLDB AS (
	SELECT table_name, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dpa_test'
)
SELECT *
FROM FULLDB
LEFT JOIN SMALLDB ON FULLDB.COLUMN_NAME = SMALLDB.COLUMN_NAME
WHERE FULLDB.DATA_TYPE <> SMALLDB.DATA_TYPE