

-- CREATE A TEXT SEARCH TABLE WITH ALL TEXT TO BE SEARCHED AS ONE FIELD

DROP TABLE
	test

SELECT 
	Id_Identity,
	UPRN,
	UDPRN,
	POSTCODE,
	CASE WHEN ORGANISATION_NAME <> '' THEN ORGANISATION_NAME + ' ' ELSE '' END +
	CASE WHEN DEPARTMENT_NAME <> '' THEN DEPARTMENT_NAME + ' ' ELSE '' END +
	CASE WHEN SUB_BUILDING_NAME <> '' THEN SUB_BUILDING_NAME + ' ' ELSE '' END +
	CASE WHEN BUILDING_NAME <> '' THEN BUILDING_NAME + ' ' ELSE '' END +
	CASE WHEN BUILDING_NUMBER IS NOT NULL THEN CAST(BUILDING_NUMBER AS NVARCHAR(10)) + ' ' ELSE '' END +
	CASE WHEN DEPENDENT_THOROUGHFARE <> '' THEN DEPENDENT_THOROUGHFARE + ' ' ELSE '' END +
	CASE WHEN THOROUGHFARE <> '' THEN THOROUGHFARE + ' ' ELSE '' END +
	CASE WHEN DOUBLE_DEPENDENT_LOCALITY <> '' THEN DOUBLE_DEPENDENT_LOCALITY + ' ' ELSE '' END +
	CASE WHEN DEPENDENT_LOCALITY <> '' THEN DEPENDENT_LOCALITY + ' ' ELSE '' END +
	CASE WHEN POST_TOWN <> '' THEN POST_TOWN + ' ' ELSE '' END +
	CASE WHEN POSTCODE <> '' THEN POSTCODE + ' ' ELSE '' END +
	CASE WHEN WELSH_DEPENDENT_THOROUGHFARE <> '' THEN WELSH_DEPENDENT_THOROUGHFARE + ' ' ELSE '' END +
	CASE WHEN WELSH_THOROUGHFARE <> '' THEN WELSH_THOROUGHFARE + ' ' ELSE '' END +
	CASE WHEN WELSH_DOUBLE_DEPENDENT_LOCALITY <> '' THEN WELSH_DOUBLE_DEPENDENT_LOCALITY + ' ' ELSE '' END +
	CASE WHEN WELSH_DEPENDENT_LOCALITY <> '' THEN WELSH_DEPENDENT_LOCALITY + ' ' ELSE '' END +
	CASE WHEN WELSH_POST_TOWN <> '' THEN WELSH_POST_TOWN + ' ' ELSE '' END 
	AS SEARCH
INTO 
	test
FROM
	delivery_point

-- ADD THE UNIQUE KEY
ALTER TABLE test
ADD CONSTRAINT PK_test
-- PRIMARY KEY(Id_Identity)
	PRIMARY KEY CLUSTERED ([Id_Identity] ASC) 
	WITH (PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]


CREATE FULLTEXT INDEX ON dbo.test(SEARCH) KEY INDEX PK_test;  

--SELECT
--	'CASE WHEN ' + COLUMN_NAME +' <> '''' THEN ' + COLUMN_NAME + ' + '' '' ELSE '''' END +'
--FROM  
--	INFORMATION_SCHEMA.COLUMNS
--WHERE
--	TABLE_NAME='delivery_point'

--RETURN
